language: node_js
dist: xenial

os:
  - linux
  - osx

node_js:
  - "12"
  - "13"
  - "14"

before_install:

install:
  - npm ci
  - npm i -g codecov
  - dev/install-zimtools.sh

script:
  - npm run lint
  - npm run build
  - REDIS=redis://127.0.0.1:6379 ZIMCHECK_PATH=`find .. -name zimcheck` npm run codecov
  - npm run jest

after_success:
  - codecov
  - ./dev/publish.sh

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - python3-pip
      - libbz2-dev
      - ccache
      - zlib1g-dev
      - uuid-dev

services:
  - redis-server
